### ISSUE TITLE
Missing ip-rate-limit in readme example

### ISSUE THREAD

**Issue by TomerG2** [staticweb-io/rate-limit#2]
Hi,

I noticed your missing ip-rate-limit in the readme example

Expected:
`(require '[io.staticweb.rate-limit.middleware :refer [wrap-rate-limit ip-rate-limit]])`

Actual:
`(require '[io.staticweb.rate-limit.middleware :refer [wrap-rate-limit]])`

**Comment by john-shaffer** [comment]
Fixed in https://github.com/staticweb-io/rate-limit/commit/983abee712c912d3a8a4efa9717e462295117efd. Thank you!
